import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";
import { ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { design } from "../../constants/design";
import { LOAD_SIZE_OPTIONS } from "../../constants/loadsizes";
import { VEHICLES } from "../../constants/vehicles";
import { DeliveryCategory, useBookingFlow } from "../../hooks/useBookingFlow";
import { AppLocation, DropoffPlace, VehicleId } from "../../types";
import { getPriceBreakdown } from "../../utils/pricing";
import { AppButton } from "../ui/app-button";
import { LocationStep } from "./LocationStep";

type Flow = ReturnType<typeof useBookingFlow>;
type Props = { flow: Flow; currentLocation: AppLocation | null; loadingLocation: boolean; submitting: boolean; onCurrentLocation: () => void; onMapPick: () => void; onSearch: (place: DropoffPlace) => void; onSubmit: () => void };
const categories: DeliveryCategory[] = ["Package", "Documents", "Shopping", "Groceries", "Electronics", "Furniture", "Food", "Other"];
export function BookingSheet({ flow, currentLocation, loadingLocation, submitting, onCurrentLocation, onMapPick, onSearch, onSubmit }: Props) {
  const isLocation = flow.step === "pickup" || flow.step === "dropoff";
  const selectLocation = (place: DropoffPlace) => flow.step === "pickup" ? flow.choosePickup({ ...place, placeId: place.id }) : flow.chooseDropoff({ ...place, placeId: place.id });
  return <View style={styles.sheet}>{flow.step !== "idle" && <TouchableOpacity style={styles.back} onPress={flow.back}><Ionicons name="arrow-back" size={20} color={design.colors.ink} /></TouchableOpacity>}<ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    {flow.step === "idle" && <><Text style={styles.title}>What do you need moved?</Text><Text style={styles.subtitle}>Start with pickup, choose a destination, then select the right vehicle.</Text><AppButton label={currentLocation ? "Use current location for pickup" : "Set pickup location"} onPress={onCurrentLocation} /></>}
    {isLocation && <LocationStep kind={flow.step as "pickup" | "dropoff"} currentLocation={currentLocation} loadingLocation={loadingLocation} onCurrent={onCurrentLocation} onSearch={selectLocation} onMapPick={onMapPick} />}
    {flow.step === "details" && <><Text style={styles.title}>What are you sending?</Text><Text style={styles.subtitle}>Choose a category to help drivers prepare. Details are optional unless you select a custom load.</Text><View style={styles.chips}>{categories.map((item) => <TouchableOpacity key={item} onPress={() => flow.setCategory(item)} style={[styles.chip, flow.category === item && styles.chipActive]}><Text style={[styles.chipText, flow.category === item && styles.chipTextActive]}>{item}</Text></TouchableOpacity>)}</View><TextInput value={flow.notes} onChangeText={flow.setNotes} placeholder="Special instructions (optional)" placeholderTextColor={design.colors.muted} style={styles.input} /><View style={styles.toggle}><Text style={styles.actionTitle}>Handle with care</Text><Switch value={flow.fragile} onValueChange={flow.setFragile} trackColor={{ true: design.colors.brand }} /></View><AppButton label="Choose load size" onPress={() => flow.setStep("load")} /></>}
    {flow.step === "load" && <><Text style={styles.title}>Select load size</Text>{LOAD_SIZE_OPTIONS.map((item) => <TouchableOpacity key={item.key} onPress={() => flow.setLoadSize(item.key)} style={[styles.option, flow.loadSize === item.key && styles.optionActive]}><Text style={styles.actionTitle}>{item.label}</Text><Text style={styles.actionMeta}>{item.weightRange} · {item.description}</Text></TouchableOpacity>)}{flow.loadSize === "Custom" && <TextInput value={flow.description} onChangeText={flow.setDescription} placeholder="Describe what you need moved (required)" placeholderTextColor={design.colors.muted} style={styles.input} />}{flow.loadSize && flow.loadSize !== "Custom" && <TextInput value={flow.description} onChangeText={flow.setDescription} placeholder="Load details (optional)" placeholderTextColor={design.colors.muted} style={styles.input} />}<AppButton label="Choose vehicle" onPress={() => flow.setStep("vehicle")} disabled={!flow.loadSize || !flow.hasValidLoadDescription} /></>}
    {flow.step === "vehicle" && <><Text style={styles.title}>Available vehicles</Text><Text style={styles.subtitle}>{flow.distanceKm} km route · about {flow.etaMinutes} min delivery</Text>{VEHICLES.filter((item) => flow.suitableVehicleIds.includes(item.id)).map((item) => { const price = getPriceBreakdown(item.id, flow.loadSize, flow.distanceKm).total; const selected = flow.selectedVehicle === item.id; return <TouchableOpacity key={item.id} onPress={() => flow.setVehicle(item.id as VehicleId)} style={[styles.vehicle, selected && styles.optionActive]}><MaterialCommunityIcons name={item.icon} size={26} color={design.colors.brand} /><View style={{ flex: 1 }}><Text style={styles.actionTitle}>{item.name}{flow.recommendedVehicle === item.id ? " · Recommended" : ""}</Text><Text style={styles.actionMeta}>{item.capacity} · arrives in ~{Math.max(5, flow.etaMinutes - 2)} min</Text></View><Text style={styles.price}>KES {price.toLocaleString()}</Text></TouchableOpacity>})}<AppButton label="Review request" onPress={() => flow.setStep("confirm")} disabled={!flow.selectedVehicle} /></>}
    {flow.step === "confirm" && <>{(() => { const breakdown = getPriceBreakdown(flow.selectedVehicle, flow.loadSize, flow.distanceKm); return <><Text style={styles.title}>Ready to request?</Text><Text style={styles.subtitle}>Pickup: {flow.pickup?.address}{"\n"}Drop-off: {flow.dropoff?.address}</Text><View style={styles.summary}><Text style={styles.actionTitle}>{VEHICLES.find((item) => item.id === flow.selectedVehicle)?.name} · {flow.loadSize}</Text><Text style={styles.actionMeta}>{flow.description || flow.category || "General delivery"}{flow.fragile ? " · Fragile" : ""}</Text><Text style={styles.actionMeta}>Base fare · KES {breakdown.baseFare.toLocaleString()}</Text><Text style={styles.actionMeta}>Distance ({flow.distanceKm} km) · KES {breakdown.distanceCharge.toLocaleString()}</Text>{breakdown.loadAdjustment > 0 && <Text style={styles.actionMeta}>Load adjustment · KES {breakdown.loadAdjustment.toLocaleString()}</Text>}<Text style={styles.total}>Estimated total · KES {breakdown.total.toLocaleString()}</Text></View><AppButton label="Request Safirisha" onPress={onSubmit} loading={submitting} /><TouchableOpacity onPress={flow.back} style={styles.edit}><Text style={styles.mapActionText}>Edit request</Text></TouchableOpacity></>; })()}</>}
  </ScrollView></View>;
}
const styles = StyleSheet.create({ sheet: { flex: 1 }, content: { paddingBottom: design.spacing.lg }, back: { width: 34, height: 34, justifyContent: "center" }, title: { ...design.typography.title, color: design.colors.ink }, subtitle: { ...design.typography.body, color: design.colors.muted, marginTop: 4, marginBottom: design.spacing.md }, chips: { flexDirection: "row", flexWrap: "wrap", gap: design.spacing.xs, marginBottom: design.spacing.md }, chip: { paddingHorizontal: design.spacing.sm, paddingVertical: 10, borderRadius: design.radius.pill, backgroundColor: design.colors.subtle }, chipActive: { backgroundColor: design.colors.brand }, chipText: { ...design.typography.caption, color: design.colors.ink }, chipTextActive: { color: design.colors.white }, input: { borderWidth: 1, borderColor: design.colors.border, padding: design.spacing.sm, borderRadius: design.radius.md, color: design.colors.ink, marginBottom: design.spacing.sm, ...design.typography.body }, toggle: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: design.spacing.md }, actionTitle: { ...design.typography.label, color: design.colors.ink }, actionMeta: { ...design.typography.caption, color: design.colors.muted, marginTop: 3 }, option: { borderWidth: 1, borderColor: design.colors.border, borderRadius: design.radius.md, padding: design.spacing.sm, marginBottom: design.spacing.xs }, optionActive: { borderColor: design.colors.brand, backgroundColor: design.colors.brandSoft }, vehicle: { flexDirection: "row", alignItems: "center", gap: design.spacing.sm, borderWidth: 1, borderColor: design.colors.border, borderRadius: design.radius.md, padding: design.spacing.sm, marginBottom: design.spacing.xs }, price: { ...design.typography.label, color: design.colors.success }, summary: { padding: design.spacing.md, backgroundColor: design.colors.subtle, borderRadius: design.radius.md, marginBottom: design.spacing.md }, total: { ...design.typography.title, color: design.colors.brand, marginTop: design.spacing.sm }, edit: { alignItems: "center", padding: design.spacing.sm }, mapActionText: { ...design.typography.label, color: design.colors.brand } });
